export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const INCREMENT = 'INCREMENT';
export const UPDATE_FILTER  = 'UPDATE_FILTER';
export const ADD_COMMENT  = 'ADD_COMMENT';

export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES';